package cc.misshi.springai.travelplanner;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

/**
 * Travel Orchestration Service — 协调 4 个 sub-agent 完成旅行规划.
 *
 * <p>0 网络 mock 模式:用规则引擎生成旅行计划,真实 LLM 时改用 sub-agent prompt.
 * <p>当 4 个 sub-agent Bean 都注入失败或为 null 时,自动走 mock 路径(测试场景).
 */
@Service
public class TravelPlannerService {

    private final ChatClient destinationAgent;
    private final ChatClient itineraryAgent;
    private final ChatClient budgetAgent;
    private final ChatClient bookingAgent;
    private final ChatClient orchestrator;

    public TravelPlannerService(
            @Qualifier("destinationAgent") ChatClient destinationAgent,
            @Qualifier("itineraryAgent") ChatClient itineraryAgent,
            @Qualifier("budgetAgent") ChatClient budgetAgent,
            @Qualifier("bookingAgent") ChatClient bookingAgent,
            @Qualifier("travelOrchestrator") ChatClient orchestrator) {
        this.destinationAgent = destinationAgent;
        this.itineraryAgent = itineraryAgent;
        this.budgetAgent = budgetAgent;
        this.bookingAgent = bookingAgent;
        this.orchestrator = orchestrator;
    }

    /**
     * 编排旅行计划:目的地 → 行程 → 预算 → 订票.
     * 0 网络走 mock 模板,真实 LLM 走 sub-agent call().
     */
    public TravelPlan plan(TravelRequest request) {
        // 0 网络:用规则直接产出,真实 LLM 时 sub-agent 都有非 null bean
        if (isMockMode()) {
            return mockPlan(request);
        }

        // 真实 LLM 路径(0 网络下走不到这里)
        String destinations = destinationAgent.prompt()
                .user("推荐 " + request.theme() + " 主题的 " + request.days() + " 天旅行目的地")
                .call().content();
        String itinerary = itineraryAgent.prompt()
                .user("为 " + destinations + " 安排 " + request.days() + " 天行程,预算 " + request.budgetCNY() + " 元")
                .call().content();
        String budget = budgetAgent.prompt()
                .user("估算 " + request.days() + " 天行程的费用,总预算 " + request.budgetCNY() + " 元")
                .call().content();
        String booking = bookingAgent.prompt()
                .user("推荐订票策略,预算 " + request.budgetCNY() + " 元")
                .call().content();

        String finalPlan = orchestrator.prompt()
                .user("整合以下子计划:\n目的地:\n" + destinations +
                        "\n行程:\n" + itinerary +
                        "\n预算:\n" + budget +
                        "\n订票:\n" + booking)
                .call().content();

        return new TravelPlan(destinations, itinerary, budget, booking, finalPlan);
    }

    private boolean isMockMode() {
        // sub-agent bean 为 null(测试场景直接 new)时走 mock
        return destinationAgent == null;
    }

    private TravelPlan mockPlan(TravelRequest req) {
        String theme = req.theme() == null ? "通用" : req.theme();
        int days = Math.max(1, req.days());
        int budget = Math.max(1000, req.budgetCNY());

        // 1. Destination — 主题→候选目的地(规则)
        String destinations = mockDestinations(theme);

        // 2. Itinerary — 按天拆分
        String itinerary = mockItinerary(theme, days);

        // 3. Budget — 简单规则
        int perDay = budget / days;
        String budgetStr = """
                | 类别    | 单日 (¥) | 小计 (¥) |
                |---------|----------|----------|
                | 住宿    | %4d     | %5d    |
                | 餐饮    | %4d     | %5d    |
                | 交通    | %4d     | %5d    |
                | 门票    | %4d     | %5d    |
                | **合计**|          | **%5d** |
                """.formatted(
                        perDay * 40 / 100, perDay * 40 / 100 * days,
                        perDay * 25 / 100, perDay * 25 / 100 * days,
                        perDay * 20 / 100, perDay * 20 / 100 * days,
                        perDay * 15 / 100, perDay * 15 / 100 * days,
                        budget);

        // 4. Booking — 通用 checklist
        String booking = """
                - [ ] 提前 30 天订机票(周二/周三最便宜)
                - [ ] 比价: 携程 / 去哪儿 / 航司官网
                - [ ] 酒店: 提前 14 天预订,可免费取消
                - [ ] 景点门票: 提前 7 天线上预订
                - [ ] 旅行保险: 出发前 3 天购买
                """;

        // 5. Final — orchestrator 整合
        String finalPlan = """
                # 🌍 %s · %d 天旅行计划

                ## 1. 目的地推荐
                %s

                ## 2. 行程安排
                %s

                ## 3. 预算估算
                %s

                ## 4. 订票策略
                %s

                ---
                *Generated by AI 旅行规划师 · 总预算 ¥%d*
                """.formatted(theme, days, destinations, itinerary, budgetStr, booking, budget);

        return new TravelPlan(destinations, itinerary, budgetStr, booking, finalPlan);
    }

    private String mockDestinations(String theme) {
        return switch (theme) {
            case "海滨" -> """
                    - **三亚**: 11-4 月最佳,亚龙湾 / 蜈支洲岛 / 天涯海角
                    - **厦门**: 3-5 月或 9-11 月,鼓浪屿 / 环岛路 / 沙坡尾
                    - **青岛**: 5-10 月,栈桥 / 八大关 / 崂山
                    """;
            case "雪山" -> """
                    - **丽江**: 11-4 月,玉龙雪山 / 蓝月谷 / 束河古镇
                    - **北海道**(日本): 12-3 月,小樽 / 函馆山 / 登别
                    - **瑞士**: 12-3 月,因特拉肯 / 少女峰 / 采尔马特
                    """;
            case "美食" -> """
                    - **成都**: 一年四季,火锅 / 串串 / 钵钵鸡
                    - **广州**: 10-3 月,早茶 / 烧腊 / 糖水
                    - **台北**: 11-4 月,夜市 / 牛肉面 / 卤肉饭
                    """;
            case "文化" -> """
                    - **北京**: 春秋季,故宫 / 长城 / 颐和园
                    - **西安**: 春秋季,兵马俑 / 大雁塔 / 古城墙
                    - **京都**(日本): 春秋季,清水寺 / 伏见稻荷 / 岚山
                    """;
            default -> """
                    - **杭州**: 春秋季,西湖 / 灵隐寺 / 西溪湿地
                    - **大理**: 春秋季,苍山洱海 / 古城 / 双廊
                    - **桂林**: 4-10 月,漓江 / 阳朔 / 兴坪古镇
                    """;
        };
    }

    private String mockItinerary(String theme, int days) {
        StringBuilder sb = new StringBuilder();
        for (int d = 1; d <= days; d++) {
            sb.append("**Day ").append(d).append("**\n");
            if (d == 1) {
                sb.append("- 🌅 上午: 抵达目的地,入住酒店\n");
                sb.append("- 🌇 下午: 城市漫步 + 当地特色午餐\n");
                sb.append("- 🌃 晚上: ").append(theme).append("主题夜游\n\n");
            } else if (d == days) {
                sb.append("- 🌅 上午: 酒店退房 + 伴手礼采购\n");
                sb.append("- 🌇 下午: 前往机场/车站\n");
                sb.append("- 🌃 晚上: 返程\n\n");
            } else {
                sb.append("- 🌅 上午: 核心景点 A\n");
                sb.append("- 🌇 下午: 核心景点 B + 主题体验\n");
                sb.append("- 🌃 晚上: ").append(theme).append("特色晚餐 + 夜景\n\n");
            }
        }
        return sb.toString().trim();
    }

    // ─── DTO ───────────────────────────────────────────

    public record TravelRequest(String theme, int days, int budgetCNY) {
        public TravelRequest {
            if (days <= 0) days = 3;
            if (budgetCNY <= 0) budgetCNY = 5000;
        }
    }

    public record TravelPlan(
            String destinations,
            String itinerary,
            String budget,
            String booking,
            String finalPlan
    ) {}
}
